title: Stackbit Azimuth Theme
baseURL: /
params:
  palette: orange
  header:
    title: RefRef
    has_nav: false
    menu:
      actions:
        - label: Sign Up
          url: /signup
  footer:
    tagline: RefRef - Referee Reference
    has_nav: false
    nav_title: Company
    has_social: false
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe to updates
    subscribe_content: Get an updated version emailed to you whenever changes are made by FIBA.
    content: All content reproduced from 
    links:
      - text: FIBA
        url: 'https://www.fiba.basketball/documents'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
