title: FIBA Rulebook designed for smartphones in ePub format
baseURL: /
params:
  palette: orange
  header:
    title: RefRef
    has_nav: true
    menu:
      actions:
        - label: Download
          url: /downloads/FIBA_Official_Basketball_Rules_2018.epub
  footer:
    tagline: RefRef (short for Referee Reference) is a website dedicated to providing useful resources to FIBA referees.
    has_nav: true
    nav_title: RefRef
    has_social: false
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe to updates
    subscribe_content: Get an updated version emailed to you whenever changes are made by FIBA.
    content: All content reproduced from 
    links:
      - text: FIBA
        url: 'https://www.fiba.basketball/documents'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true